import {
  ApplicationConfig,
  ErrorHandler,
  importProvidersFrom,
  inject,
  provideAppInitializer,
  provideZoneChangeDetection,
} from '@angular/core';
import {
  PreloadAllModules,
  provideRouter,
  withComponentInputBinding,
  withPreloading,
  withViewTransitions,
} from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideServiceWorker } from '@angular/service-worker';
import { isDevMode } from '@angular/core';
import {
  LucideAngularModule,
  House,
  FileText,
  Tag,
  Shield,
  Search,
  Bell,
  Sun,
  Moon,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronDown,
  ChevronUp,
  CircleX,
  Blocks,
  GitCompare,
  UserCheck,
  LogOut,
  User,
  Settings,
  Plus,
  Minus,
  Check,
  X,
  ArrowRight,
  ArrowUpRight,
  Inbox,
  LayoutDashboard,
  Users,
  Network,
  Lock,
  Upload,
  Trash2,
  Image,
  ImageOff,
  BookOpen,
  BarChart2,
  Building2,
  FolderOpen,
  FolderPlus,
  FolderSearch,
  Layers,
  CloudUpload,
  PlayCircle,
  Box,
  FilePen,
  HelpCircle,
  Pencil,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  AlertTriangle,
  Eye,
  EyeOff,
  Pause,
  Download,
  RotateCw,
  Copy,
  CheckCircle2,
  XCircle,
  List,
  Globe,
  Package,
  Calendar,
  CalendarClock,
  CalendarPlus,
  CalendarX,
  Loader2,
  Loader,
  PackageOpen,
  AlertCircle,
  Boxes,
  Calculator,
  Files,
  GitCommit,
  Github,
  HardDrive,
  Link,
  ListChecks,
  Mail,
  MessageSquare,
  MousePointerClick,
  Phone,
  Plug,
  RefreshCw,
  Rocket,
  Save,
  Send,
  Server,
  ExternalLink,
  GitPullRequest,
  // Page header icons
  PackagePlus,
  ClipboardCheck,
  LayoutTemplate,
  ShieldCheck,
  // Release builder category icons
  Star,
  TrendingUp,
  Wrench,
  Zap,
  Code,
  Info,
  // Dashboard KPI icons
  CheckCircle,
  Clock,
  // Builder template icons
  Map,
  Lightbulb,
  Play,
  Ticket,
  Columns2,
  Merge,
  Archive,
  History,
  RotateCcw,
  Braces,
  Bookmark,
  // Security module icons (added after runtime audit)
  CircleCheck,
  CircleOff,
  KeyRound,
  LockOpen,
  MapPinned,
  ShieldHalf,
  ShieldPlus,
  UserPlus,
  UsersRound,
  Activity,
  Fingerprint,
  FilterX,
  FilePlus2,
  LayoutGrid,
  ListTree,
  Printer,
  Ban,
  Columns,
  MonitorSmartphone,
  ScanSearch,
  SlidersHorizontal,
  Sparkles,
  CircleHelp,
  Compass,
  Construction,
} from 'lucide-angular';

import { routes } from './app.routes';
import { authInterceptor } from '@core/auth/interceptors/auth.interceptor';
import { errorInterceptor } from '@core/http/interceptors/error.interceptor';
import { loadingInterceptor } from '@core/http/interceptors/loading.interceptor';
import { AuthService } from '@core/auth/services/auth.service';
import { ThemeService } from '@core/theme/theme.service';
import { FocusOnNavigationService } from '@core/a11y/focus-on-navigation';
import { GlobalErrorHandler } from '@core/errors/global-error-handler';
import { client as generatedApiClient } from './api/generated/client.gen';
import { provideHeyApiClient } from './api/generated/client/client.gen';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(
      routes,
      withComponentInputBinding(),
      withPreloading(PreloadAllModules),
      withViewTransitions({ skipInitialTransition: true }),
    ),
    provideHttpClient(withInterceptors([authInterceptor, loadingInterceptor, errorInterceptor])),
    provideHeyApiClient(generatedApiClient),
    { provide: ErrorHandler, useClass: GlobalErrorHandler },
    provideAppInitializer(() => inject(ThemeService).init()),
    provideAppInitializer(() => inject(FocusOnNavigationService).init()),
    provideAppInitializer(() => inject(AuthService).carregarMe()),
    provideServiceWorker('ngsw-worker.js', {
      enabled: !isDevMode(),
      registrationStrategy: 'registerWhenStable:30000',
    }),
    importProvidersFrom(
      LucideAngularModule.pick({
        House,
        FileText,
        Tag,
        Shield,
        Search,
        Bell,
        Sun,
        Moon,
        ChevronLeft,
        ChevronRight,
        ChevronsLeft,
        ChevronsRight,
        ChevronDown,
        ChevronUp,
        CircleX,
        Blocks,
        GitCompare,
        UserCheck,
        LogOut,
        User,
        Settings,
        Plus,
        Minus,
        Check,
        X,
        ArrowRight,
        ArrowUpRight,
        Inbox,
        LayoutDashboard,
        Users,
        Network,
        Lock,
        Upload,
        Trash2,
        Image,
        ImageOff,
        BookOpen,
        BarChart2,
        Building2,
        FolderOpen,
        FolderPlus,
        FolderSearch,
        Layers,
        CloudUpload,
        PlayCircle,
        Box,
        FilePen,
        HelpCircle,
        Pencil,
        ArrowLeft,
        ArrowUp,
        ArrowDown,
        AlertTriangle,
        Eye,
        EyeOff,
        Pause,
        Download,
        RotateCw,
        Copy,
        CheckCircle2,
        XCircle,
        List,
        Globe,
        Package,
        Calendar,
        CalendarClock,
        CalendarPlus,
        CalendarX,
        Loader2,
        Loader,
        PackageOpen,
        AlertCircle,
        Boxes,
        Calculator,
        Files,
        GitCommit,
        Github,
        HardDrive,
        Link,
        ListChecks,
        Mail,
        MessageSquare,
        MousePointerClick,
        Phone,
        Plug,
        RefreshCw,
        Rocket,
        Save,
        Send,
        Server,
        ExternalLink,
        GitPullRequest,
        PackagePlus,
        ClipboardCheck,
        LayoutTemplate,
        ShieldCheck,
        Star,
        TrendingUp,
        Wrench,
        Zap,
        Code,
        Info,
        CheckCircle,
        Clock,
        Map,
        Lightbulb,
        Play,
        Ticket,
        Columns2,
        Merge,
        Archive,
        History,
        RotateCcw,
        Braces,
        Bookmark,
        CircleCheck,
        CircleOff,
        KeyRound,
        LockOpen,
        MapPinned,
        ShieldHalf,
        ShieldPlus,
        UserPlus,
        UsersRound,
        Activity,
        Fingerprint,
        FilterX,
        FilePlus2,
        LayoutGrid,
        ListTree,
        Printer,
        Ban,
        Columns,
        MonitorSmartphone,
        ScanSearch,
        SlidersHorizontal,
        Sparkles,
        CircleHelp,
        Compass,
        Construction,
      }),
    ),
  ],
};
