import {
  ApplicationConfig,
  importProvidersFrom,
  inject,
  provideAppInitializer,
  provideZoneChangeDetection,
} from '@angular/core';
import {
  PreloadAllModules,
  provideRouter,
  withComponentInputBinding,
  withPreloading,
  withViewTransitions,
} from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideServiceWorker } from '@angular/service-worker';
import { isDevMode } from '@angular/core';
import {
  LucideAngularModule,
  House,
  FileText,
  Tag,
  Shield,
  Search,
  Bell,
  Sun,
  Moon,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ChevronDown,
  LogOut,
  User,
  Settings,
  Plus,
  Check,
  X,
  ArrowRight,
  Inbox,
  LayoutDashboard,
  Users,
  Network,
  Lock,
  Upload,
  Trash2,
  ImageOff,
  BookOpen,
  BarChart2,
  Building2,
  FolderOpen,
  Layers,
  CloudUpload,
  PlayCircle,
  Box,
  FilePen,
  HelpCircle,
  Pencil,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  AlertTriangle,
  Eye,
  Download,
  RotateCw,
  Copy,
  CheckCircle2,
  XCircle,
  List,
  Globe,
  Package,
  Calendar,
  Loader2,
  ExternalLink,
  // Page header icons
  PackagePlus,
  ClipboardCheck,
  LayoutTemplate,
  ShieldCheck,
  // Release builder category icons
  Star,
  TrendingUp,
  Wrench,
  Zap,
  Code,
  Info,
  // Dashboard KPI icons
  CheckCircle,
  Clock,
  // Builder template icons
  Map,
  Lightbulb,
  Play,
  Ticket,
  Columns2,
  Archive,
  Bookmark,
  // Security module icons (added after runtime audit)
  CircleCheck,
  CircleOff,
  KeyRound,
  LockOpen,
  MapPinned,
  ShieldHalf,
  ShieldPlus,
  UserPlus,
  UsersRound,
} from 'lucide-angular';

import { routes } from './app.routes';
import { authInterceptor } from '@core/auth/interceptors/auth.interceptor';
import { errorInterceptor } from '@core/http/interceptors/error.interceptor';
import { loadingInterceptor } from '@core/http/interceptors/loading.interceptor';
import { AuthService } from '@core/auth/services/auth.service';
import { ThemeService } from '@core/theme/theme.service';
import { FocusOnNavigationService } from '@core/a11y/focus-on-navigation';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(
      routes,
      withComponentInputBinding(),
      withPreloading(PreloadAllModules),
      withViewTransitions({ skipInitialTransition: true }),
    ),
    provideHttpClient(withInterceptors([authInterceptor, loadingInterceptor, errorInterceptor])),
    provideAppInitializer(() => inject(ThemeService).init()),
    provideAppInitializer(() => inject(FocusOnNavigationService).init()),
    provideAppInitializer(() => inject(AuthService).carregarMe()),
    provideServiceWorker('ngsw-worker.js', {
      enabled: !isDevMode(),
      registrationStrategy: 'registerWhenStable:30000',
    }),
    importProvidersFrom(
      LucideAngularModule.pick({
        House,
        FileText,
        Tag,
        Shield,
        Search,
        Bell,
        Sun,
        Moon,
        ChevronLeft,
        ChevronRight,
        ChevronsLeft,
        ChevronsRight,
        ChevronDown,
        LogOut,
        User,
        Settings,
        Plus,
        Check,
        X,
        ArrowRight,
        Inbox,
        LayoutDashboard,
        Users,
        Network,
        Lock,
        Upload,
        Trash2,
        ImageOff,
        BookOpen,
        BarChart2,
        Building2,
        FolderOpen,
        Layers,
        CloudUpload,
        PlayCircle,
        Box,
        FilePen,
        HelpCircle,
        Pencil,
        ArrowLeft,
        ArrowUp,
        ArrowDown,
        AlertTriangle,
        Eye,
        Download,
        RotateCw,
        Copy,
        CheckCircle2,
        XCircle,
        List,
        Globe,
        Package,
        Calendar,
        Loader2,
        ExternalLink,
        PackagePlus,
        ClipboardCheck,
        LayoutTemplate,
        ShieldCheck,
        Star,
        TrendingUp,
        Wrench,
        Zap,
        Code,
        Info,
        CheckCircle,
        Clock,
        Map,
        Lightbulb,
        Play,
        Ticket,
        Columns2,
        Archive,
        Bookmark,
        CircleCheck,
        CircleOff,
        KeyRound,
        LockOpen,
        MapPinned,
        ShieldHalf,
        ShieldPlus,
        UserPlus,
        UsersRound,
      }),
    ),
  ],
};
